### PR TITLE
Added match and internal keyword

### PR DESCRIPTION
**Pull request by ovr**

### CODE REVIEW

**Comment by nkt** [comment]
@ovr what do you think about merge this plugin to original Zephir?

**Comment by ovr** [comment]
@nkt What do you mean `original Zephir`?

**Comment by nkt** [comment]
@ovr I mean `Zephir` plugin for atom. https://github.com/phalcon/zephir-atom

**Comment by ovr** [comment]
@nkt I thinks It's a good idea
Can you implement it?

**Pull request merged**
